# Generated by Django 5.0.7 on 2024-07-21 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código de Color o Característica')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicativos', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Indicativo',
                'verbose_name_plural': 'Indicativos',
            },
        ),
    ]
