# Generated by Django 5.0.7 on 2024-07-21 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_indicativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_color', models.CharField(max_length=50, verbose_name='Código de Color')),
                ('descripcion', models.TextField(verbose_name='Descripción del Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Característica de Color',
                'verbose_name_plural': 'Características de Color',
            },
        ),
        migrations.DeleteModel(
            name='Indicativo',
        ),
    ]
