# Generated by Django 5.0.7 on 2024-07-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_caracteristicacolor_delete_indicativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color_referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color de Referencia'),
        ),
    ]
