# Generated by Django 5.0.7 on 2024-07-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_color_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color_referencia',
        ),
    ]
