# Generated by Django 5.0.7 on 2024-08-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_producto_color_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(default='0000', max_length=255, verbose_name='Código del Producto'),
        ),
    ]
