# Generated by Django 5.0.7 on 2024-08-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_codigo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en Inventario'),
        ),
    ]
